"""Advanced tool features: artifacts, output types, return_direct, prepare, args validation, conditional cache.

Demonstrates the Tier 1 + Tier 2 tool features inspired by LangChain,
Pydantic-AI, and CrewAI:

1. **Tool artifact (dual return)** — LLM gets a summary, app gets the full data.
2. **Tool output types** — Structured multimodal returns (text, image, file).
3. **return_direct** — Tool result becomes final output, skipping LLM rewrite.
4. **Tool prepare** — Dynamic tool definition modifier per LLM step.
5. **Args validator** — Business logic validation (post-schema, pre-execution).
6. **Conditional cache** — Cache successful results, skip errors.

Usage:
    python examples/tools/tool_advanced_features.py
"""

from __future__ import annotations

try:
    from dotenv import load_dotenv

    load_dotenv()
except ImportError:
    pass

import logging

from troopai.adk.agents import Agent
from troopai.adk.tools.function_tool import function_tool
from troopai.adk.types.tools.tool_output_types import ToolOutputImage, ToolOutputText

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# 1. Tool Artifact (Dual Return)
# ---------------------------------------------------------------------------
# The LLM sees a concise summary. The app gets the full data on
# FunctionToolCallResult.artifact. Extends the max_result_tokens
# philosophy: instead of truncating blindly, the tool author controls
# what each consumer sees.


@function_tool(name="rag_search", description="Search knowledge base", response_format="content_and_artifact")
def rag_search(query: str) -> tuple[str, list[dict]]:
    """Search for documents matching the query."""
    # Simulate retrieval — in production this would filter by `query`.
    docs = [
        {"title": "AI Safety", "content": "Full text of document 1..." * 50},
        {"title": "Agent Frameworks", "content": "Full text of document 2..." * 50},
        {"title": "Cost Optimization", "content": "Full text of document 3..." * 50},
    ]
    summary = f"Found {len(docs)} documents for '{query}': {', '.join(d['title'] for d in docs)}"
    return summary, docs  # LLM sees summary, app gets docs


# ---------------------------------------------------------------------------
# 2. Tool Output Types (Multimodal Returns)
# ---------------------------------------------------------------------------
# Tools can return ToolOutputText, ToolOutputImage, ToolOutputFileContent
# for structured multimodal output that the framework converts to the
# appropriate LLM content parts.


@function_tool(name="generate_chart", description="Generate a chart from data")
def generate_chart(data: str) -> list:
    """Generate a chart visualization."""
    # Simulate chart generation
    chart_url = "data:image/png;base64,iVBORw0KGgoAAAANS..."
    return [
        ToolOutputText(text=f"Generated bar chart for: {data}"),
        ToolOutputImage(image_url=chart_url, detail="high"),
    ]


# ---------------------------------------------------------------------------
# 3. return_direct (Skip LLM Rewrite)
# ---------------------------------------------------------------------------
# The tool's result goes straight to the user as final_output.
# Saves one LLM round-trip for tools that produce polished output.


@function_tool(name="formatted_report", description="Generate a formatted report", return_direct=True)
def formatted_report(topic: str) -> str:
    """Generate a pre-formatted report that doesn't need LLM rewriting."""
    return f"""
    ╔══════════════════════════════╗
    ║   REPORT: {topic.upper():<17} ║
    ╠══════════════════════════════╣
    ║ Generated by analysis engine ║
    ║ Status: Complete             ║
    ╚══════════════════════════════╝
    """


# ---------------------------------------------------------------------------
# 4. Tool Prepare (Dynamic Tool Modification)
# ---------------------------------------------------------------------------
# More powerful than enabled — can modify description, restrict params,
# or exclude the tool entirely based on runtime context.

from dataclasses import replace

from troopai.adk.run.context import RunContext
from troopai.adk.tools.function_tool import FunctionTool


def prepare_api_search(ctx: RunContext, tool: FunctionTool):
    """Modify search tool based on remaining API quota."""
    remaining = ctx.context.get("api_calls_remaining", 0) if ctx.context else 0
    if remaining <= 0:
        return None  # Exclude tool — no API calls left
    return replace(
        tool,
        description=f"Search the API ({remaining} calls remaining). Use wisely.",
    )


@function_tool(name="api_search", description="Search external API", prepare=prepare_api_search)
def api_search(query: str) -> str:
    """Search an external API with limited quota."""
    return f"API results for: {query}"


# ---------------------------------------------------------------------------
# 5. Args Validator (Business Logic Validation)
# ---------------------------------------------------------------------------
# Runs after Pydantic schema validation, before execution.
# Distinct from guardrails (safety/policy) — this is about correctness.
# Raises ToolRetry to send a retry message to the LLM.


@function_tool(name="transfer_funds", description="Transfer money")
def transfer_funds(amount: float, to: str) -> str:
    """Transfer funds to a recipient.

    Business logic validation (amount limits, email format) is best
    handled by a tool input guardrail rather than a separate validator.
    """
    return f"Transferred ${amount:.2f} to {to}"


# ---------------------------------------------------------------------------
# 6. Conditional Cache Function
# ---------------------------------------------------------------------------
# Cache successful results but skip errors. More granular than cache=True.


def cache_if_success(input_args: str, result: str) -> bool:
    """Only cache successful results, not error messages.

    The ``input_args`` parameter is mandated by the ``cache_function`` callback
    contract (``Callable[[str, str], bool]``) but the decision here depends
    solely on the ``result`` payload.
    """
    del input_args  # interface-mandated but unused
    return "error" not in result.lower() and "timeout" not in result.lower()


@function_tool(
    name="weather_api",
    description="Get current weather",
    cache=True,
    cache_function=cache_if_success,
)
def weather_api(city: str) -> str:
    """Fetch weather data (cached on success only)."""
    if city.lower() == "atlantis":
        return "Error: City not found"
    return f"Weather in {city}: 72°F, sunny"


# ---------------------------------------------------------------------------
# Putting it all together
# ---------------------------------------------------------------------------

analyst = Agent(
    name="Analyst",
    system_prompt="""You are a data analyst. You have access to:
    - rag_search: Find documents (returns summary to you, full docs to app)
    - generate_chart: Create visualizations (returns multimodal content)
    - formatted_report: Generate pre-formatted reports (result goes directly to user)
    - api_search: Search external API (quota-limited, may be unavailable)
    - transfer_funds: Transfer money (validates amounts and recipients)
    - weather_api: Get weather (cached on success)

    Use the right tool for each request.""",
    tools=[rag_search, generate_chart, formatted_report, api_search, transfer_funds, weather_api],
)


if __name__ == "__main__":
    import asyncio

    async def demo():
        logger.info("=" * 60)
        logger.info("Advanced Tool Features Demo")
        logger.info("=" * 60)

        # Demo 1: Artifact — show that tool returns both summary and full data
        logger.info("\n--- 1. Tool Artifact (content_and_artifact) ---")
        logger.info(f"rag_search.response_format = {rag_search.response_format}")
        logger.info(
            "When the LLM invokes rag_search, the runner unpacks the (summary, docs) "
            "tuple: the LLM sees only the summary, while the full docs land on "
            "FunctionToolCallResult.artifact (reachable via result.new_items)."
        )

        # Demo 2: Tool output types
        logger.info("\n--- 2. Tool Output Types ---")
        logger.info("Tools can return ToolOutputText + ToolOutputImage for multimodal output")

        # Demo 3: return_direct
        logger.info("\n--- 3. return_direct ---")
        logger.info(f"formatted_report.return_direct = {formatted_report.return_direct}")
        logger.info("When this tool executes, its result becomes RunResult.final_output directly")

        # Demo 4: prepare
        logger.info("\n--- 4. Tool Prepare ---")
        prepare_name = api_search.prepare.__name__ if api_search.prepare is not None else "<none>"
        logger.info(f"api_search.prepare = {prepare_name}")
        logger.info("Tool description changes per step based on remaining API quota")

        # Demo 5: (args_validator removed — use input guardrails instead)

        # Demo 6: conditional cache
        logger.info("\n--- 6. Conditional Cache ---")
        logger.info(f"weather_api.cache = {weather_api.cache}")
        cache_fn_name = weather_api.cache_function.__name__ if weather_api.cache_function is not None else "<none>"
        logger.info(f"weather_api.cache_function = {cache_fn_name}")
        logger.info("Caches 'sunny' results but not 'Error: City not found'")

        logger.info("\n" + "=" * 60)
        logger.info("All features configured on Agent 'Analyst'")
        logger.info(f"Tools: {[t.name for t in analyst.tools]}")

    asyncio.run(demo())
