"""Agent-level input and output guardrail execution.

Runs blocking and parallel guardrails before/after agent execution,
raising tripwire exceptions when a guardrail triggers.

Provides three input guardrail entry points:
- ``run_blocking_input_guardrails`` — blocking guardrails only (sequential)
- ``run_parallel_input_guardrails`` — parallel guardrails only (concurrent)
- ``run_input_guardrails`` — convenience: blocking then parallel (for HITL paths)

And one output guardrail entry point:
- ``run_output_guardrails`` — all output guardrails (concurrent), with
  optional remediation callback for self-correction retries.

Features:
- **Severity levels**: ``AgentGuardrailSeverity`` on ``AgentGuardrailFunctionOutput``
  overrides ``tripwire_triggered`` for halt decisions. ``WARNING`` and ``INFO``
  are recorded without halting.
- **Timeout**: ``timeout`` on guardrail classes wraps execution in
  ``asyncio.wait_for()``. ``timeout_policy`` (``FAIL``/``PASS``) controls behavior.
- **Remediation**: ``AgentOutputGuardrail.remediation`` + ``on_remediate`` callback
  enables self-correction retries before raising.
"""

from __future__ import annotations

import asyncio
import dataclasses
import logging
from collections.abc import Awaitable, Callable
from typing import TYPE_CHECKING, Any

from troopai.adk.agents.agent_guardrails import AgentGuardrailSeverity, AgentTimeoutPolicy
from troopai.adk.exceptions import (
    AgentInputGuardrailTripwireTriggered,
    AgentOutputGuardrailTripwireTriggered,
)
from troopai.adk.run.governance import emit_guardrail_audit
from troopai.adk.tracing import guardrail_span

if TYPE_CHECKING:
    from troopai.adk.agents.agent import Agent
    from troopai.adk.agents.agent_guardrails import (
        AgentGuardrailFunctionOutput,
        AgentInputGuardrail,
        AgentInputGuardrailResult,
        AgentOutputGuardrail,
        AgentOutputGuardrailResult,
    )
    from troopai.adk.hooks.hooks import RunHooks
    from troopai.adk.run.context import RunContext, TContext
    from troopai.adk.run.types import UserPrompt

logger = logging.getLogger(__name__)


# ── Shared helpers ───────────────────────────────────────────


def _should_halt(output: AgentGuardrailFunctionOutput) -> bool:
    """Determine whether a guardrail result should halt execution.

    When ``severity`` is set, it overrides ``tripwire_triggered``:
    only ``ERROR`` halts. When ``severity`` is ``None``, falls back
    to ``tripwire_triggered``.
    """
    if output.severity is not None:
        return output.severity == AgentGuardrailSeverity.ERROR
    return output.tripwire_triggered


def _log_guardrail_verdict(
    output: AgentGuardrailFunctionOutput,
    guardrail_name: str,
    agent_name: str,
    guardrail_kind: str,
) -> None:
    """Log guardrail verdicts at appropriate levels based on severity."""
    if output.severity is not None:
        if output.severity == AgentGuardrailSeverity.WARNING:
            logger.warning(
                "%s guardrail '%s' warning for agent '%s': %s",
                guardrail_kind,
                guardrail_name,
                agent_name,
                output.output_info,
            )
        elif output.severity == AgentGuardrailSeverity.INFO:
            logger.debug(
                "%s guardrail '%s' info for agent '%s': %s",
                guardrail_kind,
                guardrail_name,
                agent_name,
                output.output_info,
            )
        elif output.severity == AgentGuardrailSeverity.ERROR:
            logger.info(
                "%s guardrail '%s' error (severity=ERROR) for agent '%s'",
                guardrail_kind,
                guardrail_name,
                agent_name,
            )
    elif output.tripwire_triggered:
        logger.info(
            "%s guardrail '%s' tripwire triggered for agent '%s'",
            guardrail_kind,
            guardrail_name,
            agent_name,
        )


async def _run_with_timeout(
    coro: Awaitable[AgentGuardrailFunctionOutput],
    timeout: float | None,
    timeout_policy: AgentTimeoutPolicy,
    guardrail_name: str,
    agent_name: str,
    guardrail_kind: str,
    on_timeout: Callable | None = None,
) -> tuple[AgentGuardrailFunctionOutput, bool]:
    """Run a guardrail coroutine with optional timeout.

    When timeout fires:
    1. ``timeout_policy`` determines halt/pass (framework behavior).
    2. If ``on_timeout`` callback is set, invokes it with ``AgentGuardrailTimeoutInfo``
       for custom side effects (metrics, alerting, audit logging).

    Returns:
        ``(output, timed_out)`` — ``output`` is either the guardrail's actual
        verdict or a synthetic one generated by the timeout policy. ``timed_out``
        is ``True`` only when the coroutine exceeded ``timeout`` and the
        synthetic verdict was produced; callers use it to distinguish an
        infrastructure timeout from a genuine content verdict.
    """
    from troopai.adk.agents.agent_guardrails import AgentGuardrailFunctionOutput, AgentGuardrailTimeoutInfo

    if timeout is None:
        return await coro, False

    try:
        return await asyncio.wait_for(coro, timeout=timeout), False
    except TimeoutError:
        logger.warning(
            "%s guardrail '%s' timed out after %.1fs for agent '%s' (policy=%s)",
            guardrail_kind,
            guardrail_name,
            timeout,
            agent_name,
            timeout_policy.value,
        )

        # Invoke user callback for side effects (metrics, alerting, etc.)
        if on_timeout is not None:
            info = AgentGuardrailTimeoutInfo(
                guardrail_name=guardrail_name,
                agent_name=agent_name,
                timeout=timeout,
                policy=timeout_policy,
            )
            await on_timeout(info)

        if timeout_policy == AgentTimeoutPolicy.FAIL:
            return (
                AgentGuardrailFunctionOutput(
                    tripwire_triggered=True,
                    output_info=f"Guardrail timed out after {timeout}s",
                ),
                True,
            )
        # PASS — continue silently
        return (
            AgentGuardrailFunctionOutput(
                tripwire_triggered=False,
                output_info=f"Guardrail timed out after {timeout}s (passed by policy)",
            ),
            True,
        )


# ── Input guardrails ────────────────────────────────────────


async def run_blocking_input_guardrails(
    agent: Agent,
    user_prompt: UserPrompt,
    context: RunContext[TContext],
    hooks: RunHooks[TContext],
    config_guardrails: list[AgentInputGuardrail[Any]] | None = None,
    tracing_enabled: bool = False,
    metrics_enabled: bool = False,
) -> list[AgentInputGuardrailResult]:
    """Run only blocking (run_in_parallel=False) input guardrails sequentially.

    Config guardrails run first, then agent guardrails.

    Args:
        agent: The agent whose input guardrails to run.
        user_prompt: The user's input (string or message list).
        context: The run context wrapper.
        hooks: Lifecycle hooks.
        config_guardrails: Optional global guardrails from RunConfig.
        tracing_enabled: Whether span tracing is enabled.
        metrics_enabled: Whether metric instruments are enabled.

    Returns:
        List of AgentInputGuardrailResult for all executed guardrails.

    Raises:
        AgentInputGuardrailTripwireTriggered: If any guardrail trips.
    """
    from troopai.adk.agents.agent_guardrails import (
        AgentInputGuardrailData,
        AgentInputGuardrailResult,
    )

    all_guardrails = list(config_guardrails or []) + list(agent.guardrails.input)
    blocking = [g for g in all_guardrails if not g.run_in_parallel]

    if len(blocking) == 0:
        return []

    logger.debug(
        "Running %d blocking input guardrails for agent '%s'",
        len(blocking),
        agent.name,
    )

    input_data = AgentInputGuardrailData(
        context=context,
        agent=agent,
        user_prompt=user_prompt,
    )

    all_results: list[AgentInputGuardrailResult] = []
    for guardrail in blocking:
        name = guardrail.get_name()
        logger.debug("Starting blocking input guardrail '%s'", name)
        await hooks.on_input_guardrail_start(context, agent, name)
        with guardrail_span(name=name, disabled=not (tracing_enabled or metrics_enabled)) as g_span:
            output, _ = await _run_with_timeout(
                guardrail.run(input_data),
                guardrail.timeout,
                guardrail.timeout_policy,
                name,
                agent.name,
                "Input",
                on_timeout=guardrail.on_timeout,
            )
            g_span.data = dataclasses.replace(
                g_span.data,
                triggered=output.tripwire_triggered,
                action=output.resolved_action(),
            )
        result = AgentInputGuardrailResult(guardrail=guardrail, agent=agent, guardrail_output=output)
        all_results.append(result)
        emit_guardrail_audit(
            context,
            level="agent_input",
            agent_name=agent.name,
            guardrail_name=name,
            action=output.resolved_action(),
            severity=output.severity,
            checked=user_prompt,
            changed_spans=tuple(output.changed_spans or ()),
        )
        await hooks.on_input_guardrail_end(context, agent, result)
        logger.debug(
            "Completed blocking input guardrail '%s' (tripwire=%s)",
            name,
            output.tripwire_triggered,
        )

        if _should_halt(output):
            _log_guardrail_verdict(output, name, agent.name, "Input")
            raise AgentInputGuardrailTripwireTriggered(result, all_results=all_results)

        # Log non-halting severity verdicts
        if output.severity is not None and not _should_halt(output):
            _log_guardrail_verdict(output, name, agent.name, "Input")

    return all_results


async def run_parallel_input_guardrails(
    agent: Agent,
    user_prompt: UserPrompt,
    context: RunContext[TContext],
    hooks: RunHooks[TContext],
    config_guardrails: list[AgentInputGuardrail[Any]] | None = None,
    tracing_enabled: bool = False,
    metrics_enabled: bool = False,
) -> list[AgentInputGuardrailResult]:
    """Run only parallel (run_in_parallel=True) input guardrails concurrently.

    Config guardrails and agent guardrails with run_in_parallel=True
    are executed concurrently via asyncio.gather.

    Args:
        agent: The agent whose input guardrails to run.
        user_prompt: The user's input (string or message list).
        context: The run context wrapper.
        hooks: Lifecycle hooks.
        config_guardrails: Optional global guardrails from RunConfig.
        tracing_enabled: Whether span tracing is enabled.
        metrics_enabled: Whether metric instruments are enabled.

    Returns:
        List of AgentInputGuardrailResult for all executed guardrails.

    Raises:
        AgentInputGuardrailTripwireTriggered: If any guardrail trips.
    """
    from troopai.adk.agents.agent_guardrails import (
        AgentInputGuardrailData,
        AgentInputGuardrailResult,
    )

    all_guardrails = list(config_guardrails or []) + list(agent.guardrails.input)
    parallel = [g for g in all_guardrails if g.run_in_parallel]

    if len(parallel) == 0:
        return []

    logger.debug(
        "Running %d parallel input guardrails for agent '%s'",
        len(parallel),
        agent.name,
    )

    input_data = AgentInputGuardrailData(
        context=context,
        agent=agent,
        user_prompt=user_prompt,
    )

    async def _run_guardrail(guardrail):
        name = guardrail.get_name()
        logger.debug("Starting parallel input guardrail '%s'", name)
        await hooks.on_input_guardrail_start(context, agent, name)
        with guardrail_span(name=name, disabled=not (tracing_enabled or metrics_enabled)) as g_span:
            output, _ = await _run_with_timeout(
                guardrail.run(input_data),
                guardrail.timeout,
                guardrail.timeout_policy,
                name,
                agent.name,
                "Input",
                on_timeout=guardrail.on_timeout,
            )
            g_span.data = dataclasses.replace(
                g_span.data,
                triggered=output.tripwire_triggered,
                action=output.resolved_action(),
            )
        result = AgentInputGuardrailResult(guardrail=guardrail, agent=agent, guardrail_output=output)
        emit_guardrail_audit(
            context,
            level="agent_input",
            agent_name=agent.name,
            guardrail_name=name,
            action=output.resolved_action(),
            severity=output.severity,
            checked=user_prompt,
            changed_spans=tuple(output.changed_spans or ()),
        )
        await hooks.on_input_guardrail_end(context, agent, result)
        logger.debug(
            "Completed parallel input guardrail '%s' (tripwire=%s)",
            name,
            output.tripwire_triggered,
        )
        return result

    # asyncio.gather preserves input order — results[i] corresponds to
    # parallel[i] regardless of completion order.
    results = await asyncio.gather(
        *[_run_guardrail(g) for g in parallel],
        return_exceptions=True,
    )

    all_results: list[AgentInputGuardrailResult] = []
    for result in results:
        if isinstance(result, BaseException):
            logger.warning(
                "Input guardrail raised an unexpected exception for agent '%s': %s",
                agent.name,
                result,
                exc_info=result,
            )
            raise result
        all_results.append(result)
        if _should_halt(result.guardrail_output):
            _log_guardrail_verdict(
                result.guardrail_output,
                result.guardrail.get_name(),
                agent.name,
                "Input",
            )
            raise AgentInputGuardrailTripwireTriggered(result, all_results=all_results)

        # Log non-halting severity verdicts
        if result.guardrail_output.severity is not None and not _should_halt(result.guardrail_output):
            _log_guardrail_verdict(
                result.guardrail_output,
                result.guardrail.get_name(),
                agent.name,
                "Input",
            )

    return all_results


async def run_input_guardrails(
    agent: Agent,
    user_prompt: UserPrompt,
    context: RunContext[TContext],
    hooks: RunHooks[TContext],
    config_guardrails: list[AgentInputGuardrail[Any]] | None = None,
    tracing_enabled: bool = False,
    metrics_enabled: bool = False,
) -> list[AgentInputGuardrailResult]:
    """Run all input guardrails (blocking first, then parallel).

    Convenience function that runs both blocking and parallel guardrails
    sequentially. For true parallel-with-agent execution, use
    ``run_blocking_input_guardrails`` and ``run_parallel_input_guardrails``
    separately.

    Args:
        agent: The agent whose input guardrails to run.
        user_prompt: The user's input (string or message list).
        context: The run context wrapper.
        hooks: Lifecycle hooks.
        config_guardrails: Optional global guardrails from RunConfig.
        tracing_enabled: Whether span tracing is enabled.
        metrics_enabled: Whether metric instruments are enabled.

    Returns:
        Combined list of AgentInputGuardrailResult from blocking + parallel phases.

    Raises:
        AgentInputGuardrailTripwireTriggered: If any guardrail trips.
    """
    blocking_results = await run_blocking_input_guardrails(
        agent,
        user_prompt,
        context,
        hooks,
        config_guardrails,
        tracing_enabled=tracing_enabled,
        metrics_enabled=metrics_enabled,
    )
    parallel_results = await run_parallel_input_guardrails(
        agent,
        user_prompt,
        context,
        hooks,
        config_guardrails,
        tracing_enabled=tracing_enabled,
        metrics_enabled=metrics_enabled,
    )
    return blocking_results + parallel_results


# ── Output guardrails ───────────────────────────────────────


async def _resolve_output_verdict(
    result: AgentOutputGuardrailResult,
    *,
    agent: Agent,
    on_transform: Callable[[Any], Awaitable[None]] | None,
    on_remediate: Callable[[str], Awaitable[Any]] | None,
    timed_out_names: set[str],
    transformed_names: set[str],
    remediation_counts: dict[str, int],
    all_results: list[AgentOutputGuardrailResult],
) -> Any:
    """Resolve a halting output-guardrail verdict, returning the output to
    re-validate or raising to halt the run.

    Precedence: a transform substitutes the output wholesale (once per guardrail,
    no agent re-run); else remediation re-prompts within the retry budget; else
    the tripwire is raised. A timeout-induced halt never remediates — it is an
    infrastructure failure, not a content verdict.
    """
    verdict = result.guardrail_output
    guardrail = result.guardrail
    name = guardrail.get_name()

    if verdict.transformed_output is not None and on_transform is not None and name not in transformed_names:
        # Substitute once per guardrail; the caller re-validates the replacement.
        transformed_names.add(name)
        replacement = verdict.transformed_output
        await on_transform(replacement)
        return replacement

    # A timeout-induced halt is infra failure, not content — never remediate.
    is_timeout_halt = name in timed_out_names
    if guardrail.remediation is not None and on_remediate is not None and not is_timeout_halt:
        remediation_counts.setdefault(name, 0)
        if remediation_counts[name] < guardrail.max_retries:
            remediation_counts[name] += 1
            logger.info(
                "Output guardrail '%s' triggered remediation for agent '%s' (attempt %d/%d)",
                name,
                agent.name,
                remediation_counts[name],
                guardrail.max_retries,
            )
            return await on_remediate(guardrail.remediation)
        logger.info(
            "Output guardrail '%s' remediation exhausted for agent '%s' after %d attempts",
            name,
            agent.name,
            guardrail.max_retries,
        )

    _log_guardrail_verdict(verdict, name, agent.name, "Output")
    raise AgentOutputGuardrailTripwireTriggered(result, all_results=all_results)


async def run_output_guardrails(
    agent: Agent,
    output: Any,
    ctx_wrapper: RunContext[TContext],
    hooks: RunHooks[TContext],
    config_guardrails: list[AgentOutputGuardrail[Any]] | None = None,
    on_remediate: Callable[[str], Awaitable[Any]] | None = None,
    on_transform: Callable[[Any], Awaitable[None]] | None = None,
    tracing_enabled: bool = False,
    metrics_enabled: bool = False,
) -> list[AgentOutputGuardrailResult]:
    """Run output guardrails, re-validating after each transform or remediation.

    Config guardrails run first, then the agent's, all in parallel. A halting
    verdict is resolved by :func:`_resolve_output_verdict`: substitute
    (``on_transform``), re-prompt (``on_remediate``), or raise. The substituted or
    re-prompted output is re-validated until every guardrail passes or one raises.

    ``on_transform`` is an async ``(replacement) -> None`` callback the runner
    wires to substitute a transform verdict's replacement onto the run result;
    with none wired, a transform-mode verdict falls through to its tripwire.

    Returns the executed guardrail results. Raises
    ``AgentOutputGuardrailTripwireTriggered`` on an unresolved halt.
    """

    all_guardrails = list(config_guardrails or []) + list(agent.guardrails.output)

    if len(all_guardrails) == 0:
        return []

    remediation_counts: dict[str, int] = {}
    transformed_names: set[str] = set()
    current_output = output

    while True:
        results, timed_out_names = await _run_output_guardrails_once(
            agent,
            current_output,
            ctx_wrapper,
            hooks,
            all_guardrails,
            tracing_enabled=tracing_enabled,
            metrics_enabled=metrics_enabled,
        )
        for result in results:
            if not _should_halt(result.guardrail_output):
                if result.guardrail_output.severity is not None:
                    _log_guardrail_verdict(
                        result.guardrail_output,
                        result.guardrail.get_name(),
                        agent.name,
                        "Output",
                    )
                continue
            # A halting verdict is substituted, re-prompted, or raised. A returned
            # output (transform or remediation) is re-validated by the while loop.
            current_output = await _resolve_output_verdict(
                result,
                agent=agent,
                on_transform=on_transform,
                on_remediate=on_remediate,
                timed_out_names=timed_out_names,
                transformed_names=transformed_names,
                remediation_counts=remediation_counts,
                all_results=results,
            )
            break
        else:
            return results


async def _run_output_guardrails_once(
    agent: Agent,
    output: Any,
    ctx_wrapper: RunContext[TContext],
    hooks: RunHooks[TContext],
    all_guardrails: list[AgentOutputGuardrail[Any]],
    tracing_enabled: bool = False,
    metrics_enabled: bool = False,
) -> tuple[list[AgentOutputGuardrailResult], set[str]]:
    """Run all output guardrails once in parallel.

    Returns ``(results, timed_out_names)`` without raising — the caller
    handles halt decisions and remediation. ``timed_out_names`` holds the
    names of guardrails whose verdict was synthesized by a timeout (an
    infrastructure failure) rather than produced by the guardrail itself,
    so the caller can skip content-remediation retries for them.
    """
    from troopai.adk.agents.agent_guardrails import (
        AgentOutputGuardrailData,
        AgentOutputGuardrailResult,
    )

    logger.debug(
        "Running %d output guardrails for agent '%s'",
        len(all_guardrails),
        agent.name,
    )

    output_data = AgentOutputGuardrailData(
        context=ctx_wrapper,
        agent=agent,
        output=output,
    )

    async def _run_guardrail(guardrail) -> tuple[AgentOutputGuardrailResult, bool]:
        name = guardrail.get_name()
        logger.debug("Starting output guardrail '%s'", name)
        await hooks.on_output_guardrail_start(ctx_wrapper, agent, name)
        with guardrail_span(name=name, disabled=not (tracing_enabled or metrics_enabled)) as g_span:
            guardrail_output, timed_out = await _run_with_timeout(
                guardrail.run(output_data),
                guardrail.timeout,
                guardrail.timeout_policy,
                name,
                agent.name,
                "Output",
                on_timeout=guardrail.on_timeout,
            )
            g_span.data = dataclasses.replace(
                g_span.data,
                triggered=guardrail_output.tripwire_triggered,
                action=guardrail_output.resolved_action(),
            )
        result = AgentOutputGuardrailResult(
            guardrail=guardrail,
            agent=agent,
            agent_output=output,
            guardrail_output=guardrail_output,
        )
        emit_guardrail_audit(
            ctx_wrapper,
            level="agent_output",
            agent_name=agent.name,
            guardrail_name=name,
            action=guardrail_output.resolved_action(),
            severity=guardrail_output.severity,
            checked=output,
            transformed=guardrail_output.transformed_output,
            changed_spans=tuple(guardrail_output.changed_spans or ()),
        )
        await hooks.on_output_guardrail_end(ctx_wrapper, agent, result)
        logger.debug(
            "Completed output guardrail '%s' (tripwire=%s)",
            name,
            guardrail_output.tripwire_triggered,
        )
        return result, timed_out

    # asyncio.gather preserves input order — results[i] corresponds to
    # all_guardrails[i] regardless of completion order.
    results = await asyncio.gather(
        *[_run_guardrail(g) for g in all_guardrails],
        return_exceptions=True,
    )

    all_results: list[AgentOutputGuardrailResult] = []
    timed_out_names: set[str] = set()
    for result in results:
        if isinstance(result, BaseException):
            logger.warning(
                "Output guardrail raised an unexpected exception for agent '%s': %s",
                agent.name,
                result,
                exc_info=result,
            )
            raise result
        guardrail_result, timed_out = result
        all_results.append(guardrail_result)
        if timed_out:
            timed_out_names.add(guardrail_result.guardrail.get_name())

    return all_results, timed_out_names
