"""Swarm yield signals — the explicit control-transfer primitives.

A ``SwarmYieldSignal`` is the typed payload a member agent emits to
end its turn within a swarm run. It is generated by the runner
(``turn_resolution.py``) when an agent calls one of two policy-injected
tools:

- ``transfer_to_<name>`` — generated by ``LLMHandoffPolicy`` for each
  peer member; emitted as ``SwarmHandoff``.
- ``swarm_done`` — generated by every policy (LLM / round-robin /
  structured / custom); emitted as ``SwarmDone``.

Absence of either tool call is not a termination. The swarm keeps
running until the ``TerminationCondition`` fires or a hard guard in
``SwarmConfig`` trips. This rule is what prevents the "silent
false-complete" failure mode seen in Strands Swarm.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any

SWARM_DONE_TOOL_NAME: str = "swarm_done"
"""Name of the auto-injected termination tool.

Every ``SwarmPolicy`` injects this tool (merged into the active
agent's tool list at turn dispatch, never mutating the agent config).
The LLM calls it with a ``reason`` argument to explicitly terminate
the swarm. Paired with ``ExplicitDoneTermination``.
"""


@dataclass(frozen=True)
class SwarmHandoff:
    """Explicit handoff from one swarm member to another.

    Produced when the active agent calls a
    ``transfer_to_<target>`` tool injected by ``LLMHandoffPolicy``.
    The ``message`` field carries the handoff payload — analogous to
    AutoGen's ``HandoffMessage.content`` — so the next agent receives
    an explicit briefing rather than having to infer context.

    Attributes:
        target: Name of the target member agent. MUST match a name in
            ``Swarm.members``.
        message: Explicit handoff content passed to the target agent.
            Surfaces as the user-facing message the target agent sees
            on its first turn.
    """

    target: str
    """Name of the target member agent. MUST match a name in ``Swarm.members``."""

    message: str
    """Explicit handoff content passed to the target agent. Surfaces as
    the user-facing message the target agent sees on its first turn."""


@dataclass(frozen=True)
class SwarmDone:
    """Explicit swarm termination signal.

    Produced when any agent calls the ``swarm_done`` tool. The
    ``final_output`` is the terminal agent's last assistant message
    (or structured output if the agent has an ``output_schema``).

    Attributes:
        reason: Why the swarm is terminating. The LLM supplies this as
            the ``reason`` argument to ``swarm_done``. Surfaced on
            ``SwarmDoneEvent.reason`` and ``StopReason.detail``.
        final_output: The terminal agent's final output. Type depends
            on whether the agent has a structured ``output_schema``
            (pydantic model) or produces plain text (``str``).
    """

    reason: str
    """Why the swarm is terminating. The LLM supplies this as the
    ``reason`` argument to ``swarm_done``. Surfaced on
    ``SwarmDoneEvent.reason`` and ``StopReason.detail``."""

    final_output: Any
    """The terminal agent's final output. Type depends on whether the
    agent has a structured ``output_schema`` (pydantic model) or
    produces plain text (``str``)."""


SwarmYieldSignal = SwarmHandoff | SwarmDone
"""Discriminated union of the two explicit swarm control signals."""
