"""End-to-end workspace editor: V4A patches via LocalSubprocessSandbox.

Spins up a local-subprocess sandbox session, materializes a tiny
manifest with one file, then runs ``WorkspaceEditor.apply_patch``
to update, rename, and finally delete a file — verifying each
step against the live workspace.

The editor is provider-agnostic: switch to Docker, K8s, or any
hosted backend by changing the client construction below; the
patch flow is identical.

No external API key required (no LLM call).
"""

from __future__ import annotations

try:
    from dotenv import load_dotenv

    load_dotenv()
except ImportError:
    pass

import asyncio
import logging
from pathlib import Path

from troopai.adk.sandbox.apply_patch import WorkspaceEditor
from troopai.adk.sandbox.clients.local import LocalSubprocessSandboxClient
from troopai.adk.sandbox.editor import ApplyPatchOperation
from troopai.adk.types.sandbox.entries import File
from troopai.adk.types.sandbox.manifest import Manifest

logger = logging.getLogger(__name__)


async def main() -> None:
    manifest = Manifest(
        root="/tmp/troopai-workspace-demo",
        entries={
            "src/app.py": File(content=b"alpha\nbeta\ngamma\n"),
        },
    )

    client = LocalSubprocessSandboxClient()
    session = await client.create(manifest=manifest)
    try:
        await session.start()
        # Materialize the manifest's File entries onto the live workspace
        # — apply_manifest does NOT happen implicitly on start(); the
        # caller decides when to project entries onto disk.
        import io as _io

        await session.mkdir(Path("src"), parents=True)
        await session.write(Path("src/app.py"), _io.BytesIO(b"alpha\nbeta\ngamma\n"))

        editor = WorkspaceEditor(session)

        # 1. Update: rewrite the middle line.
        logger.info("=== Update src/app.py ===")
        update_op = ApplyPatchOperation(
            type="update_file",
            path="src/app.py",
            diff="@@\n alpha\n-beta\n+BETA\n+inserted\n gamma",
        )
        result = await editor.apply_operation(update_op)
        logger.info("Result: %s", result.output)
        # Verify the change landed on disk.
        post_update = await _read_file(session, Path("src/app.py"))
        assert "BETA" in post_update
        assert "beta" not in post_update

        # 2. Rename: move src/app.py to src/main.py while applying another edit.
        logger.info("=== Rename src/app.py → src/main.py ===")
        rename_op = ApplyPatchOperation(
            type="update_file",
            path="src/app.py",
            diff="@@\n alpha\n BETA\n inserted\n-gamma\n+gamma_renamed",
            move_to="src/main.py",
        )
        result = await editor.apply_operation(rename_op)
        logger.info("Result: %s", result.output)
        moved = await _read_file(session, Path("src/main.py"))
        assert "gamma_renamed" in moved

        # 3. Create: drop a fresh file into the workspace.
        logger.info("=== Create README.md ===")
        create_op = ApplyPatchOperation(
            type="create_file",
            path="README.md",
            diff="+# Demo\n+\n+Generated by the WorkspaceEditor example.",
        )
        result = await editor.apply_operation(create_op)
        logger.info("Result: %s", result.output)
        readme = await _read_file(session, Path("README.md"))
        assert readme.startswith("# Demo")

        # 4. Delete: clean up.
        logger.info("=== Delete README.md ===")
        delete_op = ApplyPatchOperation(type="delete_file", path="README.md")
        result = await editor.apply_operation(delete_op)
        logger.info("Result: %s", result.output)

        logger.info("All editor operations succeeded.")
    finally:
        await session.aclose()


async def _read_file(session: object, path: Path) -> str:
    handle = await session.read(path)  # type: ignore[attr-defined]
    try:
        data = handle.read()
    finally:
        handle.close()
    if isinstance(data, bytes | bytearray):
        return bytes(data).decode("utf-8")
    return str(data)


if __name__ == "__main__":
    asyncio.run(main())
