"""Types module for TroopAI Agents.

This module provides type definitions for:
- Input/output message types
- Chat message types (provider-agnostic Chat Completions format)
- Tool configuration and definition types
- Built-in tool call/result types
- Handoff types
- Response types
- Result types
"""

from troopai.adk.types.items import (
    CompactionItem,
    HandoffCallItem,
    HandoffOutputItem,
    ItemHelpers,
    MCPApprovalRequestItem,
    MCPApprovalResponseItem,
    MCPListToolsItem,
    MessageOutputItem,
    ReasoningItem,
    RunItem,
    RunItemBase,
    SystemItem,
    ToolApprovalItem,
    ToolCallItem,
    ToolCallOutputItem,
    ToolSearchCallItem,
    ToolSearchOutputItem,
    UserItem,
)
from troopai.adk.types.run import RunResult
from troopai.adk.types.tools.builtin_tool_types import (
    ApplyPatchToolCall,
    ApplyPatchToolCallResult,
    CodeInterpreterOutput,
    CodeInterpreterToolCall,
    CodeInterpreterToolCallResult,
    ComputerAction,
    ComputerToolCall,
    ComputerToolCallResult,
    FileSearchResult,
    FileSearchToolCall,
    FileSearchToolCallResult,
    ImageGenerationToolCall,
    ImageGenerationToolCallResult,
    MCPApprovalRequest,
    MCPApprovalResponse,
    MCPCall,
    MCPCallResult,
    MCPListTools,
    MCPListToolsTool,
    ShellToolCall,
    ShellToolCallResult,
    ToolSearchResultEntry,
    ToolSearchToolCall,
    ToolSearchToolCallResult,
    WebSearchResult,
    WebSearchToolCall,
    WebSearchToolCallResult,
)
from troopai.adk.types.tracing import (
    AgentSpanData,
    AnySpanData,
    CustomSpanData,
    FunctionSpanData,
    GenerationSpanData,
    GuardrailSpanData,
    HandoffSpanData,
    ResponseSpanData,
    SpanData,
)

__all__ = [
    "AgentSpanData",
    "AnySpanData",
    # Built-in tool call/result types
    "ApplyPatchToolCall",
    "ApplyPatchToolCallResult",
    "CodeInterpreterOutput",
    "CodeInterpreterToolCall",
    "CodeInterpreterToolCallResult",
    "CompactionItem",
    "ComputerAction",
    "ComputerToolCall",
    "ComputerToolCallResult",
    "CustomSpanData",
    "FileSearchResult",
    "FileSearchToolCall",
    "FileSearchToolCallResult",
    "FunctionSpanData",
    "GenerationSpanData",
    "GuardrailSpanData",
    "HandoffCallItem",
    "HandoffOutputItem",
    "HandoffSpanData",
    "ImageGenerationToolCall",
    "ImageGenerationToolCallResult",
    "ItemHelpers",
    "MCPApprovalRequest",
    "MCPApprovalRequestItem",
    "MCPApprovalResponse",
    "MCPApprovalResponseItem",
    "MCPCall",
    "MCPCallResult",
    "MCPListTools",
    "MCPListToolsItem",
    "MCPListToolsTool",
    "MessageOutputItem",
    "ReasoningItem",
    "ResponseSpanData",
    # Run items
    "RunItem",
    "RunItemBase",
    # Result
    "RunResult",
    "ShellToolCall",
    "ShellToolCallResult",
    # Tracing span data
    "SpanData",
    "SystemItem",
    "ToolApprovalItem",
    "ToolCallItem",
    "ToolCallOutputItem",
    "ToolSearchCallItem",
    "ToolSearchOutputItem",
    "ToolSearchResultEntry",
    "ToolSearchToolCall",
    "ToolSearchToolCallResult",
    "UserItem",
    "WebSearchResult",
    "WebSearchToolCall",
    "WebSearchToolCallResult",
]
